#!/bin/sh

EXTDIR="/usr/lib/enigma2/python/Plugins/Extensions/TivuStream/"

if [ -d "$EXTDIR" ]; then
   rm -rf "$EXTDIR" > /dev/null 2>&1
fi

#rm -rf /usr/lib/enigma2/python/Plugins/Extensions/TiVuStream
#opkg remove enigma2-plugin-extensions-tivustream

#cd /etc/enigma2
#sed -i '/userbouquet.tivustream/d' 'bouquets.tv'
#rm -f /etc/enigma2/userbouquet.tivustream*.tv
#sed -i '/userbouquet.tivustream/d' '/etc/enigma2/bouquets.radio'
#rm -f /etc/enigma2/userbouquet.tivustream_radio.radio
#cd /

#while ! ping -c 1 google.it &>/dev/null; do sleep 1;done;
#echo 'Reloading Services, Please Wait'
#wget -q -O - http://127.0.0.1/web/servicelistreload?mode=2 > /dev/null 2>&1


echo "..TiVuStream .."
echo "***********************************"
echo "*         by Lululla              *"
echo "***********************************"
echo "***********************************"
echo "*     E2 Restart Is Required      *"
echo "***********************************"
exit 0
